---
- name: "Install required packages on CentOS "
  yum:
    name: "{{ item }}"
  with_items:
    - unzip
    - tar
    - wget
    - curl
    - git

- name: check for updates (yum)
  yum: list=updates update_cache=true
  register: yum_output

- name: debug
  debug: var=yum_output
  msg: "{{ yum_output.results | map(attribute='name') | list }}
