---
- name: "Install required packages on CentOS"
  ansible.builtin.yum:
    name: "{{ item }}"
  with_items: "{{ custom_packages }}"

- name: Check for updates (yum)
  ansible.builtin.yum:
    list: updates
    update_cache: true
  register: yum_output

- name: Debug
  ansible.builtin.debug:
    msg: "{{ yum_output.results | map(attribute='name') | list }}"
