---
- name: "Install specific packages on Ubuntu"
  ansible.builtin.apt:
    pkg:
      - apache
      - ca-certificates
      - python3-pip
      - software-properties-common

- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  register: apt_output

- name: debug
  ansible.builtin.debug:
    msg: "{{ apt_output.results | map(attribute='name') | list }}"
