---
- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
  register: apt_output

- name: debug
  ansible.builtin.debug:
    msg: "{{ apt_output }}"

- name: Install specific packages on Ubuntu
  ansible.builtin.apt:
    name: "{{ custom_packages }}"
    update_cache: yes
    cache_valid_time: 3600
