---
- name: Load OS-specific vars.
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: Debug - print OS family and distribution
  ansible.builtin.debug:
    msg: "{{ ansible_os_family }} {{ ansible_distribution }}"

- name: Include Centos specific checks
  ansible.builtin.include_tasks: checks-centos.yml
  when: ansible_distribution == 'Centos'

- name: Include Ubuntu specific checks
  ansible.builtin.include_tasks: checks-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
