---
- name: Load OS-specific vars.
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - default.yml
      paths:
        - 'vars'

- name: Debug
  msg: "{{ ansible_os_family }} {{ ansible_distribution }}"

- name: Include Centos specific checks
  ansible.builtin.include_tasks: checks-centos.yml
  when: ansible_os_family == 'centos'

- name: Include Ubuntu specific checks
  ansible.builtin.include_tasks: checks-ubuntu.yml
  when: ansible_os_family == 'ubuntu'
