---
- name: Load OS specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
  - files:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower | replace('/', '_') }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower | replace('/', '_') }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    skip: true

- name: Debug - print OS family and distribution
  ansible.builtin.debug:
    msg: "{{ ansible_os_family }} {{ ansible_distribution }}"

- name: Include Centos specific checks
  ansible.builtin.include_tasks: checks-centos.yml
  when: ansible_distribution == 'Centos'

- name: Include Ubuntu specific checks
  ansible.builtin.include_tasks: checks-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
