---
- name: include Linux distro-specific vars
  include_vars: "{{ item }}"
  with_first_found:
  - files:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower | replace('/', '_') }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower | replace('/', '_') }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    skip: true

- name: include Linux distro-specific checks
  include: "{{ prerequisites_file }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower | replace('/', '_') }}.yml"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower | replace('/', '_') }}.yml"
      - "{{ ansible_distribution | lower }}.yml"
      - "{{ ansible_os_family | lower }}.yml"
      skip: true
  loop_control:
    loop_var: prerequisites_file
