---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: instance-ubuntu
    image: ubuntu:lunar
  - name: instance-centos7
    image: centos:7

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    verify: verify.yml
