---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Get packages facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Verify if packages are installed
      ansible.builtin.assert:
        that:
          - "{{ item }}" in ansible_facts.packages
      register: result
      failed_when: result is failed
      changed_when: result is changed
      with: "{{ packages }}"
