---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Get packages facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages }}"

    - name: Verify if packages are installed
      ansible.builtin.assert:
        that:
          - ansible_facts.packages[item] | length > 0
      with_items: 
        - "{{ packages }}"
      register: result
      failed_when: result is failed
      changed_when: result is changed
