---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Get packages facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['curl'] }}"

    - name: Verify if packages are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)
      with_items: "{{ custom_packages }}"
