---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Get packages facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
      ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
      vars:
        params:
          files:
            - "{{ ansible_distribution|lower() }}-{{ ansible_distribution_major_version|lower() }}.yml"
            - "{{ ansible_distribution|lower() }}.yml"
            - "{{ ansible_os_family|lower() }}.yml"
            - default.yaml
          paths:
            - '../../vars'

    - name: Verify if packages are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)
      with_items: "{{ custom_packages }}"

    - name: Verify if packages are installed with assert
      ansible.builtin.assert:
        that:
          - packages[item.name] is defined
        success_msg: "Package '{{ item.name }}' is installed"
        fail_msg: "Package '{{ item.name }}' is not installed!"
      loop: "{{ custom_packages }}"
      loop_control:
        loop_var: item
